### ISSUE TITLE
about parameter shapeIndex in sloshing.xml

### ISSUE THREAD

**Issue by pkestene** [doyubkim/fluid-engine-dev-demo#3]
I've just built mitsuba to try fluid-engine-dev demos and
I've noticed that currently the rendering fails:
[...]
2017-11-25 21:34:19 INFO  main [WavefrontOBJ] Done with "100_ani_0.6,0.9.obj" (took 2315 ms)
Caught a critical exception: main [WavefrontOBJ] Assertion "m_meshes.size() > 0" failed in /home/pkestene/install/Visu/mitsuba/github/mitsuba/src/shapes/obj.cpp:740

This seems to be related to parameter shapeIndex (currently set to value "2") in section
shape type="obj" id="water" of sloshing.xml

If I change this shapeIndex value to -1 for this object, the rendering works fine. 

Can someone reproduce this behavior ? I'd like to understand.
Thank you.

**Comment by doyubkim** [comment]
Thanks for reporting the issue, @pkestene!

I haven't tested with the latest Mitsuba built from the source, but I used pre-built binaries from the website (http://mitsuba-renderer.org/download.html). However, parameter `shapeIndex` doesn't make sense to be defined for `obj` type in the first place, so I made a PR (#4) that removes the unused parameters. If you can checkout my branch `rm_shape_index` and confirm that it fixes the problem, please let me know.

Thanks,
Doyub

**Comment by pkestene** [comment]
@doyubkim Thanks for the quick fix !

**Comment by doyubkim** [comment]
You’re welcome! The fix is now merged.
